name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  write-all

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn clean test
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: JaCoCo Code Coverage Report
        id: jacoco_reporter
        uses: PavanMudigonda/jacoco-reporter@v4.8
        with:
          coverage_results_path: target/my-reports/jacoco.xml
          coverage_report_name: Coverage
          coverage_report_title: JaCoCo
          github_token: ${{ secrets.GITHUB_TOKEN }}
          skip_check_run: false
          minimum_coverage: 90
          fail_below_threshold: false
          publish_only_summary: false

      # Publish Coverage Job Summary  # Optional
      - name: Add Coverage Job Summary
        run: echo "${{ steps.jacoco_reporter.outputs.coverageSummary }}" >> $GITHUB_STEP_SUMMARY

      - name: Badge Action
        uses: emibcn/badge-action@v2.0.2
        with:
          label: 'Test coverage'
          status: '{{ GITHUB_STEP_SUMMARY }}'
          color: 'blue,555,daf'
          path: '.github/badges/coverage.svg'

      - name: Generate badge
        uses: actions/upload-artifact@v3
        with:
          name: badge.svg
          path: ./badge.svg

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    
      - name: Commit and Push Generated Files
        run: |
          git config --global user.email "stefanomerinoderui@gmail.com"
          git config --global user.name "Billones142"
          
          git checkout -- src/
          rm -rf src
          git add src/

          git checkout -- .gitignore
          rm .gitignore
          git add .gitignore

          git checkout -- openTest.bat
          rm openTest.bat
          git add openTest.bat

          git checkout -- pom.xml
          rm pom.xml
          git add pom.xml

          git checkout -- README.md
          rm README.md
          
          git add target/my-reports/*
          git commit -m "Add generated files"
          git push --force https://$GH_TOKEN@github.com/Billones142/TP2-GestorEmails.git HEAD:reports
